import { Link } from 'react-router-dom';
import { business, PRIVACY_VERSION, SIC_URL } from '../data/legal';
import { buildWhatsAppLink } from '../utils/whatsappGenerator';

export default function PrivacyPage() {
  return <main className="legal-page shop-shell">
    <Link to="/" className="product-back">Volver al inicio</Link>
    <h1>Política de Tratamiento de Datos Personales</h1>
    <p>Versión {PRIVACY_VERSION} · Colombia</p>
    <section><h2>Responsables y contacto</h2><p>{business.legalName}, bajo la marca ALPEZ Joyería, atienden las solicitudes sobre datos personales por los siguientes canales:</p>
      <ul>{business.responsiblePeople.map(person => <li key={person.identification}>{person.name} · {person.identification}</li>)}</ul>
      <ul>{business.nit && <li>NIT: {business.nit}</li>}{business.address && <li>Dirección: {business.address}</li>}{business.email && <li>Correo: <a href={`mailto:${business.email}`}>{business.email}</a></li>}<li>WhatsApp: <a href={buildWhatsAppLink('Hola. Quiero realizar una solicitud sobre mis datos personales.')} target="_blank" rel="noopener noreferrer">{business.phone}</a></li></ul>
    </section>
    <section><h2>Datos y finalidades</h2><p>El registro es opcional: puedes consultar el catálogo y solicitar una compra por WhatsApp sin crear una cuenta. Al registrarte tratamos nombre, correo y datos de autenticación para administrar el acceso y atender solicitudes relacionadas con tu cuenta.</p><p>Cuando solicitas una compra, tratamos los datos que entregues para atenderla, coordinar la entrega, registrar la venta, gestionar garantías y cumplir obligaciones legales. El registro interno de ventas incluye nombre y teléfono del cliente, artículos, valores, fecha y responsable de la atención. No solicitamos datos sensibles ni datos de tarjetas de pago en esta web. Estos usos no incluyen el envío de publicidad; cualquier finalidad publicitaria requerirá una autorización separada.</p></section>
    <section><h2>Autorización</h2><p>La autorización de registro se solicita mediante una casilla sin marcar previamente y se asocia a la cuenta junto con la versión del texto aceptado. Para datos entregados por WhatsApp o de forma presencial, se informarán las finalidades y se solicitará y conservará la autorización correspondiente antes de registrarlos, salvo una excepción legal aplicable. Abrir un enlace o navegar no equivale a autorizar cualquier uso de tus datos.</p></section>
    <section><h2>Tus derechos</h2><p>Puedes conocer, actualizar y rectificar tus datos; solicitar prueba de la autorización y conocer su uso; acceder gratuitamente a la información y solicitar la supresión o revocar la autorización cuando proceda. La supresión puede estar limitada por obligaciones legales o contractuales de conservación. Puedes acudir a la <a href={SIC_URL} target="_blank" rel="noopener noreferrer">Superintendencia de Industria y Comercio (SIC)</a> una vez agotado el trámite que corresponda ante el responsable.</p></section>
    <section><h2>Consultas y reclamos</h2><p>Escribe al canal de contacto anterior indicando tu nombre, medio de respuesta, solicitud y la información necesaria para localizar el registro. Solo se pedirá la verificación de identidad necesaria para proteger tus datos. El contacto de atención de ALPEZ recibe estas solicitudes.</p><p>Las consultas se atenderán en hasta 10 días hábiles; si no es posible, se informará el motivo y la nueva fecha, con una ampliación máxima de 5 días hábiles. Los reclamos completos se atenderán en hasta 15 días hábiles contados desde el día siguiente a su recepción, prorrogables por hasta 8 días hábiles con aviso motivado. Si falta información, se solicitará completarla dentro de los 5 días siguientes; después de 2 meses sin respuesta se entenderá desistido el reclamo.</p></section>
    <section><h2>Servicios y almacenamiento</h2><p>La web utiliza Supabase para autenticación y almacenamiento, Vercel para alojamiento y Cloudinary para imágenes del catálogo. Estos proveedores pueden procesar información en infraestructura fuera de Colombia. Su uso debe limitarse a las finalidades informadas y sujetarse a las garantías contractuales y legales aplicables. Al abrir WhatsApp o redes sociales utilizas un servicio externo sujeto también a sus propias políticas.</p><p>El navegador guarda la sesión y los identificadores y cantidades del carrito para mantener esas funciones. Puedes borrar el carrito o cerrar sesión; borrar los datos del navegador también elimina ese almacenamiento local.</p></section>
    <section><h2>Conservación y cambios</h2><p>La información se conserva durante el tiempo necesario para las finalidades autorizadas y los deberes legales, contractuales y de atención de reclamaciones. Cumplidos esos fines, corresponde eliminarla o anonimizarla de forma segura. Las modificaciones se informarán en esta página; los cambios sustanciales de finalidad requieren la autorización que corresponda.</p><p>Esta versión se aplicará desde su publicación definitiva. Marco normativo: Ley 1581 de 2012 y Decreto 1074 de 2015.</p></section>
  </main>;
}
